In [1]:
from sklearn.linear_model import LinearRegression

In [8]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('marks.csv')

In [6]:
data

name  duration  marks
0  abhi         4     40
1  eric         6     60
2  jack         2     20
3  amit         6     60

In [7]:
x=data['duration']
y=data['marks']
print(x,y)

0    4
1    6
2    2
3    6
Name: duration, dtype: int64 0    40
1    60
2    20
3    60
Name: marks, dtype: int64


In [18]:
X=(np.array(x.values)).reshape((len(x),1))

In [19]:
X

array([[4],
       [6],
       [2],
       [6]], dtype=int64)

In [20]:
model=LinearRegression()

In [21]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [30]:
model.predict([[9]])
# we have to pass the value to be predicted in 2-d array

array([90.])

### HOW TO SAVE AND LOAD THE SKLEARN MODEL

In [34]:
## SAVING
from sklearn.externals.joblib import dump
## pass the model and the filename the file is saves as pickle foramat so generally the extension is pk1
## dump function is used here just like pickle
dump(model,'markspredictor')
### or
from sklearn.externals import joblib
joblib.dump(model,'markspredict.pk1')

['markspredict.pk1']

In [36]:
### Loading the model
from sklearn.externals.joblib import load
newmodel=load('markspredictor')
newmodel2=load('markspredict.pk1')



In [37]:
newmodel.predict([[2.4]])


array([24.])

In [38]:

newmodel2.predict([[8.5]])

array([85.])