## Numpy

In [17]:
from numpy import array,zeros,reshape

In [1]:
l=[1,2,3,4,5]

In [3]:
a=array(l)
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [5]:
a.dtype

dtype('int32')

In [9]:
b=zeros(5)
b

array([0., 0., 0., 0., 0.])

In [10]:
print(b.shape)
print(b.dtype)

(5,)
float64


In [16]:
c=zeros([3,3])
## we have to paas the dimentions in array/list or tuple

In [13]:
print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [49]:
c=c+5

In [50]:
c

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [52]:
c=c*5
c

array([[125., 125., 125.],
       [125., 125., 125.],
       [125., 125., 125.]])

In [18]:
## tuple is preferred
d=zeros((4,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
data=array([['mohit',111],['shobhit',222],['abc',333],['def',444],['ghi',555]])
data

array([['mohit', '111'],
       ['shobhit', '222'],
       ['abc', '333'],
       ['def', '444'],
       ['ghi', '555']], dtype='<U7')

In [26]:
data[1:3,1:]
## using slicing [rows,columns]

array([['222'],
       ['333']], dtype='<U7')

In [28]:
data[:,1:]

array([['111'],
       ['222'],
       ['333'],
       ['444'],
       ['555']], dtype='<U7')

In [30]:
data.dtype
## if any data is string it makes whole data as string (unicode)

dtype('<U7')

In [31]:
data.shape

(5, 2)

In [39]:
l=[1,2,3,4,5,6,7,8,9]
e=reshape(l,(3,3))
# reshape list l into 3*3 array
# reshape used as function first argument list second tuple of shape

In [35]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
type(e)

numpy.ndarray

In [37]:
print(e.shape)
print(e.dtype)

(3, 3)
int32


In [44]:
f=array(l)
f=f.reshape(3,3)
## reshape can also be used as method for an numpy array
## this one is preferred
## remeber reshape returns an array. it doesn't works as inplace

In [45]:
print(f.shape)
print(f.dtype)
f

(3, 3)
int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
f[1][1]=99
f

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [57]:
f[:1]=1
f

array([[ 1,  1,  1],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [60]:
f[:,1:2]=2
f

array([[2, 2, 1],
       [2, 2, 6],
       [2, 2, 9]])

In [62]:
f[0][0]=88
f

array([[88,  2,  1],
       [ 2, 88,  6],
       [ 2,  2,  9]])

In [65]:
## f=99 will change the f from numpy array to int type don't do that, use f[:] instead
f[:]=55
f

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [81]:
k=zeros((3,3))+6

In [82]:
k

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

## Pandas

In [66]:
import pandas as pd

In [67]:
data=pd.read_csv('marks.csv')

In [68]:
data

name  duration  marks
0  abhi         4     40
1  eric         6     60
2  jack         2     20
3  amit         6     60

In [70]:
type(data)

pandas.core.frame.DataFrame

In [73]:
data['name']

0    abhi
1    eric
2    jack
3    amit
Name: name, dtype: object

In [74]:
data['marks']

0    40
1    60
2    20
3    60
Name: marks, dtype: int64

In [72]:
# we can pass dataset COLUMNS in the aggregate functions whichever is applicablelike: 
sum(data['marks'])

180

In [75]:
# filtering data : 
data['marks']==60

0    False
1     True
2    False
3     True
Name: marks, dtype: bool

In [78]:
data['duration']>2

0     True
1     True
2    False
3     True
Name: duration, dtype: bool

In [79]:
## using filered boolean to get filtered data rows
data[data['duration']>2]

name  duration  marks
0  abhi         4     40
1  eric         6     60
3  amit         6     60

In [80]:
## The dataset only gives response according to the data available , example duration =8 isn't in data
data[data['duration'] == 8]

Empty DataFrame
Columns: [name, duration, marks]
Index: []

## Opencv

In [1]:
import cv2 as cv

In [10]:
photo=cv.imread('bckp/award.jpg')

In [11]:
print(type(photo))
photo

<class 'numpy.ndarray'>


array([[[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       ...,

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]]], dtype=uint8)

In [12]:
cv.imshow('frame',photo)
cv.waitKey()
cv.destroyAllWindows()

In [13]:
photo.shape

(1365, 2048, 3)

In [15]:
## converting color shade from BGR to Gray
newphoto=cv.cvtColor(photo,cv.COLOR_BGR2GRAY)
print(newphoto.shape)
newphoto

(1365, 2048)


array([[12, 12, 12, ...,  7,  7,  7],
       [12, 12, 12, ...,  7,  7,  7],
       [12, 12, 12, ...,  7,  7,  7],
       ...,
       [ 7,  7,  8, ...,  7,  7,  7],
       [ 7,  7,  8, ...,  7,  7,  7],
       [ 7,  7,  8, ...,  7,  7,  7]], dtype=uint8)

In [16]:
cv.imshow('gray_scale',newphoto)
cv.waitKey()
cv.destroyAllWindows()

In [19]:
## printing some images
# color coding id BGR ==> opposite of RGB
a=zeros((200,200))+255
cv.imshow('white',a)
cv.waitKey()
cv.destroyAllWindows()

In [21]:
b=zeros((200,200))
cv.imshow('black',b)
cv.waitKey()
cv.destroyAllWindows()


In [49]:
### trying with 3d images
blue=array([[[255,0,0] for j in range(500)] for i in range(500)],dtype='uint8')
green=array([[[0,255,0] for j in range(500)] for i in range(500)],dtype='uint8')
red=array([[[0,0,255] for j in range(500)] for i in range(500)],dtype='uint8')

In [51]:
print(type(red))
print(type(green))
print(type(blue))
print(red.shape)
type(red)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(500, 500, 3)


numpy.ndarray

In [52]:
cv.imshow('red',red)
cv.waitKey()
cv.destroyAllWindows()

In [53]:
cv.imshow('green',green)
cv.waitKey()
cv.destroyAllWindows()

In [54]:
cv.imshow('blue',blue)
cv.waitKey()
cv.destroyAllWindows()

### Question how to remove red color from image

In [57]:
im=cv.imread('bckp/photo.jpg')

In [58]:
cv.imshow('original',im)
cv.waitKey()
cv.destroyAllWindows()

In [65]:
## red is the third value in [B,G,R]
im[:,:,2]=0

In [66]:
im

array([[[34, 18,  0],
        [34, 18,  0],
        [34, 18,  0],
        ...,
        [36, 17,  0],
        [37, 18,  0],
        [37, 18,  0]],

       [[35, 19,  0],
        [35, 19,  0],
        [35, 19,  0],
        ...,
        [36, 17,  0],
        [37, 18,  0],
        [37, 18,  0]],

       [[36, 20,  0],
        [36, 20,  0],
        [36, 20,  0],
        ...,
        [36, 17,  0],
        [37, 18,  0],
        [37, 18,  0]],

       ...,

       [[37, 17,  0],
        [36, 17,  0],
        [34, 16,  0],
        ...,
        [36, 18,  0],
        [36, 18,  0],
        [36, 18,  0]],

       [[38, 18,  0],
        [38, 18,  0],
        [37, 18,  0],
        ...,
        [36, 18,  0],
        [36, 18,  0],
        [36, 18,  0]],

       [[38, 18,  0],
        [39, 19,  0],
        [38, 19,  0],
        ...,
        [36, 18,  0],
        [36, 18,  0],
        [36, 18,  0]]], dtype=uint8)

In [69]:
### red values are removed
cv.imshow('Red_removed',im)
cv.waitKey()
cv.destroyAllWindows()

In [71]:
from random import randint as rd

In [72]:
img=array([[[rd(0, 256),rd(0, 256),rd(0, 256)] for j in range(500)] for i in range(500)],dtype='uint8')

In [74]:
cv.imshow('Random Image',img)
cv.waitKey()
cv.destroyAllWindows()